### ISSUE TITLE
Request: Method to fetch subscribers by custom field value

### ISSUE THREAD

**Issue by NicheDiver** [DripEmail/drip-dot-net#5]
"If we are missing an API method that you need to use in your application, please file an issue and/or open a pull request."

I am looking to fetch subscribers who have CustomField _________ that equals _________ as is currently possible via the web interface. (image attached)  Will you please add an API method for this functionality?

Thank you for your time.

![dripfilterbycustomfieldvalue](https://cloud.githubusercontent.com/assets/19387051/15287566/6cfd86c4-1b29-11e6-82d4-706b394962d5.png)

**Comment by djreimer** [comment]
Thanks @NicheDiver! This one is in our backlog. No ETA just yet, but we will be sure to notify you of any new developments.
