### ISSUE TITLE
Nuget packages

### ISSUE THREAD

**Issue by bherila** [DripEmail/drip-dot-net#8]
Could you release Nuget packages?

Thanks,
Ben

**Comment by eganlohman** [comment]
Seconded.  But thanks for creating the wrapper!

**Comment by sunniejai** [comment]
+1

**Comment by quade1664** [comment]
+1 please

**Comment by tiltsoftware** [comment]
+1 please would love a Nuget package. Thanks for creating this!

**Comment by jdconley** [comment]
I'm working on this, as well as a dependency update, presently. Just getting things squared away with LeadPages for how to publish. It should be available fairly soon. You can see my branch if you're curious.  https://github.com/jdconley/drip-dot-net/tree/update-deps

**Comment by jdconley** [comment]
This is done. Please see the master branch Readme.
