### ISSUE TITLE
Incompatible with newer restSharp DLL

### ISSUE THREAD

**Issue by quade1664** [DripEmail/drip-dot-net#9]
We have 3 things in our project which require the newer restSharp dll version

However, it seems this project is not compatible with the newer restSharp DLL
Would it be possible to fix?

**Comment by quade1664** [comment]
For anyone else facing this
Upgrade to newer restShartp.dll 
then add namespace 
using RestSharp.Authenticators;
to the file which fails to build

**Comment by jdconley** [comment]
This is done. Please see the master branch. The latest version is now in NuGet as well.
